### ISSUE TITLE
Tabs mit doppelter Bezeichnung

### ISSUE THREAD

**Issue by mj1985** [contao-bootstrap/components#10]
Wenn man zwei verschiedene Reiter mit 2 gleichen Elementnamen einfügt, dann sind die letzten Tabs nicht anwählbar, dafür wechseln die die Reiter dann in dem ersten Reiter.

Beispiel:
`<a href="#tab-programmierung" data-toggle="tab">Programmierung</a>`
und dann etwas weiter unten auf der Seite erneute eine Reitergruppe mit der gleichen Reiterbezeichnung:
`<a href="#tab-programmierung" data-toggle="tab">Programmierung</a>`

**Comment by dmolineus** [comment]
@mj1985  I've moved the issue to the new contao-bootstrap/navigation component. Please subscribe the issue contao-bootstrap/tab#1 if you want to be recognized of changed.
