### ISSUE TITLE
navbar miss responsiv button without header section

### ISSUE THREAD

**Issue by Taleteller** [contao-bootstrap/components#11]
When having a menu, without selected to display a title header, but with selecting to be responsive, the menu vanishes entirely below 768px resolution. The reason is within the template file /components/module/templates/navbar.html5. 

The condition for displaying the resonsive button is nested within the conditon for the header:
```
<?php if($this->bootstrap_addHeader): ?>
	<div class="navbar-header">
		<?php include $this->getTemplate($this->bootstrap_navbarBrandTemplate); ?>

		<?php if($this->bootstrap_isResponsive): ?>
			<?php include $this->getTemplate('navbar_toggle'); ?>
		<?php endif; ?>
	</div>
<?php endif; ?>
```

Appending the following lines behind this section, fixes the problem:
```
<?php if(!$this->bootstrap_addHeader): ?>
	<?php if($this->bootstrap_isResponsive): ?>
		<div class="navbar-header">
		<?php include $this->getTemplate('navbar_toggle'); ?>
		</div>
	<?php endif; ?>
<?php endif; ?>
```
The responsive toggle button will be shown within a header even without a title.

Regards
Thomas

**Comment by dmolineus** [comment]
@Taleteller I've moved the issue to the new contao-bootstrap/navigation component. Please subscribe the issue contao-bootstrap/navigation#2 if you want to be recognized of changed.
